global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nexus-signal-engine'
    static_configs:
      - targets: ['nexus-signal-engine:8000']
    metrics_path: '/metrics'